import { createFileRoute, Link } from "@tanstack/react-router";
import { BookOpen, Gamepad2, Signal, Swords, Users } from "lucide-react";
import { BattlefieldBackdrop, GeneralsBrand, MiniStat, Ornament, PageFrame, Panel } from "@/components/generals-ui";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

export const Route = createFileRoute("/home")({
  head: () => ({ meta: [{ title: "Home — GENERALS" }, { name: "description", content: "Command your army and conquer the battlefield in GENERALS." }, { property: "og:title", content: "Home — GENERALS" }, { property: "og:description", content: "Command your army and conquer the battlefield in GENERALS." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: HomePage,
});

function HomePage() {
  return <PageFrame><BattlefieldBackdrop><main className="mx-auto flex min-h-[calc(100vh-129px)] max-w-[1536px] flex-col items-center justify-center px-6 pb-8 pt-14 text-center"><Ornament/><h1 className="mt-4"><GeneralsBrand large /></h1><p className="mt-3 font-serif text-2xl text-foreground sm:text-3xl">Strategy. Territory. Victory.</p><div className="my-6 flex items-center gap-2 text-gold"><span className="h-px w-20 bg-gold/70"/><span className="rotate-45 text-xs">◆</span><span className="h-px w-20 bg-gold/70"/></div><p className="text-lg text-muted-foreground">Join a game, command your army, and conquer the map.</p><div className="mt-9 flex w-full max-w-[540px] flex-col gap-5 sm:flex-row"><Button asChild variant="game" className="h-20 flex-1"><Link to="/player-details"><Swords className="size-8"/><span className="text-left"><b className="block text-lg">Play Now</b><small className="font-normal opacity-80">Find or Create a Room</small></span></Link></Button><Dialog><DialogTrigger asChild><Button variant="gameOutline" className="h-20 flex-1"><BookOpen className="size-8"/><span className="text-left"><b className="block text-lg">How to Play</b><small className="font-normal text-muted-foreground">Learn the Basics</small></span></Button></DialogTrigger><DialogContent className="panel-surface border-panel-border bg-panel-strong"><DialogHeader><DialogTitle className="font-brand text-2xl text-gold">How to Play</DialogTitle><DialogDescription>Expand territory, build armies, and capture the enemy general.</DialogDescription></DialogHeader><ol className="space-y-3 text-sm"><li><b className="text-gold">1.</b> Select your territory.</li><li><b className="text-gold">2.</b> Move into an adjacent tile.</li><li><b className="text-gold">3.</b> Conquer the opposing general.</li></ol></DialogContent></Dialog></div><Panel className="mt-10 flex w-full max-w-[1280px] flex-col divide-y divide-border md:flex-row md:divide-x md:divide-y-0"><MiniStat icon={<Users className="size-9"/>} label="Players Online" value="42" detail="Across all rooms" green/><MiniStat icon={<Gamepad2 className="size-9"/>} label="Active Rooms" value="8" detail="Join an existing game"/><MiniStat icon={<Signal className="size-9"/>} label="Server Status" value="Online" detail="Ready to play" green/></Panel></main></BattlefieldBackdrop></PageFrame>;
}