import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Link2, Plus, RefreshCw, Users } from "lucide-react";
import { useState } from "react";
import { BattlefieldBackdrop, PageFrame, PageTitle, Panel } from "@/components/generals-ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { rooms, teamColours } from "@/lib/mock-data";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/play")({
  head: () => ({ meta: [{ title: "Play — GENERALS" }, { name: "description", content: "Create or join a GENERALS battlefield." }, { property: "og:title", content: "Play — GENERALS" }, { property: "og:description", content: "Create or join a GENERALS battlefield." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PlayPage,
});

function RangeRow({label, value, setValue}:{label:string;value:number;setValue:(v:number)=>void}) { return <label className="block"><span className="mb-1 flex justify-between text-xs"><span>{label}</span><b>{value.toFixed(2)}</b></span><input aria-label={label} type="range" min="0" max="1" step="0.05" value={value} onChange={e=>setValue(Number(e.target.value))} className="h-1.5 w-full cursor-pointer accent-primary"/></label> }

function PlayPage() {
  const navigate=useNavigate({from:"/play"}); const [colour,setColour]=useState("Blue"); const [width,setWidth]=useState(.5); const [height,setHeight]=useState(.5); const [mountains,setMountains]=useState(.3); const [cities,setCities]=useState(.2); const [swamps,setSwamps]=useState(.2); const [code,setCode]=useState(""); const [busy,setBusy]=useState(false);
  const enter=()=>{setBusy(true);window.setTimeout(()=>navigate({to:"/waiting-room"}),300)};
  return <PageFrame footerStats><BattlefieldBackdrop compact><PageTitle title="PLAY" subtitle="Create a room or join an existing one."/></BattlefieldBackdrop><main className="mx-auto grid max-w-[1536px] gap-3 px-4 py-3 xl:grid-cols-[510px_1fr]">
    <Panel className="p-4"><header className="mb-4 flex gap-3"><span className="grid size-10 place-items-center rounded-full bg-primary"><Plus/></span><div><h2 className="font-bold">Create a New Room</h2><p className="text-xs text-muted-foreground">Configure your game settings and invite others.</p></div></header><div className="space-y-4 text-sm"><label className="grid items-center gap-2 sm:grid-cols-[125px_1fr]"><span>Room Name</span><Input placeholder="Enter room name (e.g. Finals, Fun Match)"/></label><label className="grid items-center gap-2 sm:grid-cols-[125px_1fr]"><span>Players per Team</span><select className="h-9 rounded-md border border-input bg-background/40 px-3"><option>1 Player (1v1)</option><option>2 Players (2v2)</option></select></label><div><span>Team Colour(s)</span><div className="mt-2 grid grid-cols-6 gap-2">{teamColours.map(([name,css])=><button key={name} onClick={()=>setColour(name)} aria-label={name} className={cn("rounded-md border bg-background/30 p-2 text-[10px] transition",colour===name?"border-primary":"border-border hover:border-muted-foreground")}><i className={cn("mx-auto mb-1 block size-6 rounded-full",css)}/>{name}</button>)}</div></div><label className="grid items-center gap-2 sm:grid-cols-[125px_1fr]"><span>Game Speed</span><select className="h-9 rounded-md border border-input bg-background/40 px-3"><option>Normal</option><option>Fast</option><option>Slow</option></select></label><div className="grid grid-cols-2 gap-5"><RangeRow label="Map Width" value={width} setValue={setWidth}/><RangeRow label="Map Height" value={height} setValue={setHeight}/></div><div className="grid grid-cols-3 gap-4"><RangeRow label="Mountains" value={mountains} setValue={setMountains}/><RangeRow label="Cities" value={cities} setValue={setCities}/><RangeRow label="Swamps" value={swamps} setValue={setSwamps}/></div><div><span>Modifiers</span><div className="mt-2 grid grid-cols-2 gap-2 text-xs">{["Fog of War","Allow Death Spectator","Reveal King","Warring States Mode"].map((m,i)=><label key={m} className="flex gap-2"><input type="checkbox" defaultChecked={i<2} className="accent-primary"/>{m}</label>)}</div></div><Button variant="game" className="w-full" onClick={enter} disabled={busy}><Plus/>{busy?"Creating…":"Create Room"}</Button></div></Panel>
    <div className="space-y-3"><Panel className="p-4"><header className="mb-2 flex items-center gap-3"><Link2 className="text-primary"/><div><h2 className="font-bold">Join a Room with Code</h2><p className="text-xs text-muted-foreground">Enter a room code to join directly.</p></div></header><div className="flex gap-3"><Input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Enter room code (e.g. ABCD)"/><Button variant="game" onClick={enter} disabled={!code}>Join</Button></div></Panel><Panel className="overflow-hidden"><header className="flex items-center justify-between p-4"><div className="flex items-center gap-3"><Users className="text-primary"/><div><h2 className="font-bold">Available Rooms</h2><p className="text-xs text-muted-foreground">Join an open room and start playing.</p></div></div><Button variant="gameOutline" size="sm"><RefreshCw/>Refresh</Button></header><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-secondary/70 text-muted-foreground"><tr>{["Room Name","Players","Map Size","Speed","Terrain (M/C/S)","Modifiers","Status","Action"].map(h=><th key={h} className="px-3 py-2 font-normal">{h}</th>)}</tr></thead><tbody>{rooms.map(room=><tr key={room.name} className="border-t border-border/60 odd:bg-background/15"><td className="px-3 py-2 font-medium">{room.name}</td><td className="px-3 py-2"><span className="flex items-center gap-1">{room.colours.map((c,i)=><i key={i} className={cn("size-3 rounded-full",c)}/>)} {room.players}</span></td><td className="px-3 py-2">{room.size}</td><td className="px-3 py-2">{room.speed}</td><td className="px-3 py-2">{room.terrain}</td><td className="px-3 py-2 text-gold">♟ ♛ ⚔</td><td className="px-3 py-2"><span className="flex items-center gap-2"><i className={cn("size-2 rounded-full",room.status==="Waiting"?"bg-success":"bg-primary")}/>{room.status}</span></td><td className="px-3 py-2"><Button size="sm" variant={room.status==="Waiting"?"game":"secondary"} disabled={room.status!=="Waiting"} onClick={enter}>{room.status==="Waiting"?"Join":"Full"}</Button></td></tr>)}</tbody></table></div></Panel></div>
  </main></PageFrame>;
}